## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  #- osx
  
julia:
  - 1.5
  - nightly
  
matrix:
  allow_failures:
    - os: osx
    - julia: nightly

branches:
  only:
    - master
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    
notifications:
  email: true

git:
  depth: 99999999

